create table public.deva_accmed_enrollments (
  id bigint generated by default as identity not null,
  provider_user_id bigint not null,
  client_user_id bigint not null,
  product_id bigint not null,
  start_day timestamp with time zone null,
  days_left integer null,
  investment real null,
  decision_matrix_status text null,
  status text not null default 'active'::text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone null,
  constraint deva_accmed_enrollments_pkey primary key (id),
  constraint fk_deva_accmed_enrollments_client_user_id foreign KEY (client_user_id) references deva_accmed_users (id) on update RESTRICT on delete RESTRICT,
  constraint fk_deva_accmed_enrollments_product_id foreign KEY (product_id) references deva_accmed_products (id) on update RESTRICT on delete RESTRICT,
  constraint fk_deva_accmed_enrollments_provider_user_id foreign KEY (provider_user_id) references deva_accmed_users (id) on update RESTRICT on delete RESTRICT,
  constraint chk_deva_accmed_enrollments_provider_client_diff check ((provider_user_id <> client_user_id)),
  constraint chk_deva_accmed_enrollments_status_allowed check (
    (
      status = any (
        array[
          'active'::text,
          'finished'::text,
          'suspended'::text,
          'canceled by client'::text,
          'canceled by organization'::text
        ]
      )
    )
  ),
  constraint chk_deva_accmed_enrollments_days_left_non_negative check (
    (
      (days_left is null)
      or (days_left >= 0)
    )
  )
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_deva_accmed_enrollments_triplet_idx on public.deva_accmed_enrollments using btree (provider_user_id, client_user_id, product_id) TABLESPACE pg_default;

create index IF not exists ix_deva_accmed_enrollments_provider_user_id on public.deva_accmed_enrollments using btree (provider_user_id) TABLESPACE pg_default;

create index IF not exists ix_deva_accmed_enrollments_client_user_id on public.deva_accmed_enrollments using btree (client_user_id) TABLESPACE pg_default;

create index IF not exists ix_deva_accmed_enrollments_product_id on public.deva_accmed_enrollments using btree (product_id) TABLESPACE pg_default;

create table public.deva_accmed_organizations (
  id bigint generated by default as identity not null,
  name text not null,
  brand_name text not null,
  slug text not null,
  cnpj text null,
  timezone text not null,
  currency text not null,
  status text not null,
  is_active boolean not null default true,
  notes text null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  deleted_at timestamp with time zone null,
  constraint deva_accmed_organizations_pkey primary key (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_deva_accmed_organizations_slug_idx on public.deva_accmed_organizations using btree (slug) TABLESPACE pg_default;

create table public.deva_accmed_product_metrics (
  id bigint generated by default as identity not null,
  pillar_id bigint not null,
  name text not null,
  slug text not null,
  direction text not null,
  unit text null,
  scoring_rules jsonb not null,
  score_type text not null,
  min_score real null,
  max_score real null,
  max_score_basis text null,
  mcv real null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone null,
  constraint deva_accmed_product_metrics_pkey primary key (id),
  constraint fk_deva_accmed_product_metrics_pillar_id foreign KEY (pillar_id) references deva_accmed_product_pillars (id) on update RESTRICT on delete RESTRICT
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_deva_accmed_product_metrics_pillar_slug_idx on public.deva_accmed_product_metrics using btree (pillar_id, slug) TABLESPACE pg_default;

create index IF not exists ix_deva_accmed_product_metrics_pillar_id on public.deva_accmed_product_metrics using btree (pillar_id) TABLESPACE pg_default;

create table public.deva_accmed_products (
  id bigint generated by default as identity not null,
  organization_id bigint not null,
  name text not null,
  slug text not null,
  category text not null,
  status text not null,
  description text null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  deleted_at timestamp with time zone null,
  constraint deva_accmed_products_pkey primary key (id),
  constraint fk_deva_accmed_products_organization_id foreign KEY (organization_id) references deva_accmed_organizations (id) on update RESTRICT on delete RESTRICT
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_deva_accmed_products_slug_idx on public.deva_accmed_products using btree (slug) TABLESPACE pg_default;

create index IF not exists ix_deva_accmed_products_organization_id on public.deva_accmed_products using btree (organization_id) TABLESPACE pg_default;

create table public.deva_accmed_runtime_measurements (
  id text not null,
  enrollment_id text not null,
  metric_id text not null,
  value_baseline double precision not null,
  value_current double precision not null,
  value_projected double precision null,
  improving_trend boolean null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone null,
  constraint deva_accmed_runtime_measurements_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_deva_accmed_runtime_measurements_enrollment on public.deva_accmed_runtime_measurements using btree (enrollment_id) TABLESPACE pg_default;

create unique INDEX IF not exists idx_deva_accmed_runtime_measurements_enrollment_metric_unique on public.deva_accmed_runtime_measurements using btree (enrollment_id, metric_id) TABLESPACE pg_default;

create table public.deva_accmed_runtime_checkpoints (
  id text not null,
  enrollment_id text not null,
  week integer not null,
  status text not null,
  label text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone null,
  constraint deva_accmed_runtime_checkpoints_pkey primary key (id)
) TABLESPACE pg_default;

create index IF not exists idx_deva_accmed_runtime_checkpoints_enrollment on public.deva_accmed_runtime_checkpoints using btree (enrollment_id) TABLESPACE pg_default;

create unique INDEX IF not exists idx_deva_accmed_runtime_checkpoints_enrollment_week_unique on public.deva_accmed_runtime_checkpoints using btree (enrollment_id, week) TABLESPACE pg_default;

create table public.deva_accmed_users (
  id bigint generated by default as identity not null,
  email text not null,
  role text not null,
  full_name text not null,
  is_active boolean not null default true,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  organization_id bigint null,
  constraint deva_accmed_users_pkey primary key (id),
  constraint fk_deva_accmed_users_organization_id foreign KEY (organization_id) references deva_accmed_organizations (id) on update RESTRICT on delete set null
  , deleted_at timestamp with time zone null
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_deva_accmed_users_email_lower_idx on public.deva_accmed_users using btree (lower(email)) TABLESPACE pg_default;

create index IF not exists ix_deva_accmed_users_organization_id on public.deva_accmed_users using btree (organization_id) TABLESPACE pg_default;