CREATE TABLE IF NOT EXISTS deva_accmed_organizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  brand_name TEXT NOT NULL,
  slug TEXT NOT NULL,
  cnpj TEXT,
  timezone TEXT NOT NULL,
  currency TEXT NOT NULL,
  status TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_deva_accmed_organizations_slug_idx
  ON deva_accmed_organizations (slug);

INSERT INTO deva_accmed_organizations (
  name,
  brand_name,
  slug,
  cnpj,
  timezone,
  currency,
  status,
  is_active,
  notes,
  created_at,
  updated_at
) VALUES
  (
    'Acelerador Medico',
    'Acelerador Medico',
    'org_accmed',
    '',
    'America/Sao_Paulo',
    'BRL',
    'active',
    TRUE,
    NULL,
    '2026-03-15T05:25:51.063897Z'::timestamptz,
    '2026-03-30T19:48:45.409769Z'::timestamptz
  ),
  (
    'Innovai Solutions',
    'INNOVAI',
    'org_innovai',
    '',
    'America/Sao_Paulo',
    'BRL',
    'active',
    TRUE,
    NULL,
    '2026-03-30T15:24:21.645968Z'::timestamptz,
    '2026-03-30T15:24:21.645968Z'::timestamptz
  )
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  brand_name = EXCLUDED.brand_name,
  cnpj = EXCLUDED.cnpj,
  timezone = EXCLUDED.timezone,
  currency = EXCLUDED.currency,
  status = EXCLUDED.status,
  is_active = EXCLUDED.is_active,
  notes = EXCLUDED.notes,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;
