CREATE TABLE IF NOT EXISTS deva_accmed_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  category TEXT NOT NULL,
  status TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

ALTER TABLE deva_accmed_products
  ADD COLUMN IF NOT EXISTS organization_id BIGINT,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS slug TEXT,
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS uq_deva_accmed_products_slug_idx
  ON deva_accmed_products (slug);

CREATE INDEX IF NOT EXISTS ix_deva_accmed_products_organization_id
  ON deva_accmed_products (organization_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_deva_accmed_products_organization_id'
  ) THEN
    ALTER TABLE deva_accmed_products
      ADD CONSTRAINT fk_deva_accmed_products_organization_id
      FOREIGN KEY (organization_id)
      REFERENCES deva_accmed_organizations (id)
      ON UPDATE RESTRICT
      ON DELETE RESTRICT;
  END IF;
END $$;

WITH source_rows (
  legacy_organization_id,
  name,
  slug,
  category,
  status,
  description,
  created_at,
  updated_at
) AS (
  VALUES
    (
      '1',
      'Mentoria Acelerador Medico',
      'mnt_accmed',
      'mentoring',
      'active',
      NULL,
      '2026-03-15T06:45:48.612001Z'::timestamptz,
      '2026-03-30T19:48:45.745639Z'::timestamptz
    ),
    (
      '1',
      'Master Acelerador Medico',
      'mst_accmed',
      'mastermind',
      'active',
      NULL,
      '2026-03-30T15:24:22.045833Z'::timestamptz,
      '2026-03-30T15:24:22.045833Z'::timestamptz
    )
),
organization_mapping (legacy_organization_id, organization_slug) AS (
  VALUES
    ('cli_1', 'org_accmed'),
    ('1', 'org_accmed'),
    ('cli_2', 'org_innovai'),
    ('2', 'org_innovai')
)
INSERT INTO deva_accmed_products (
  organization_id,
  name,
  slug,
  category,
  status,
  description,
  created_at,
  updated_at
)
SELECT
  o.id AS organization_id,
  s.name,
  s.slug,
  s.category,
  s.status,
  s.description,
  s.created_at,
  s.updated_at
FROM source_rows AS s
JOIN organization_mapping AS m
  ON m.legacy_organization_id = s.legacy_organization_id
JOIN deva_accmed_organizations AS o
  ON o.slug = m.organization_slug
ON CONFLICT (slug) DO UPDATE SET
  organization_id = EXCLUDED.organization_id,
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  status = EXCLUDED.status,
  description = EXCLUDED.description,
  created_at = EXCLUDED.created_at,
  updated_at = EXCLUDED.updated_at;

-- Validacao rapida pos-migracao
SELECT
  o.slug AS organization_slug,
  o.name AS organization_name,
  COUNT(p.id) AS products_count
FROM deva_accmed_organizations AS o
LEFT JOIN deva_accmed_products AS p
  ON p.organization_id = o.id
GROUP BY o.slug, o.name
ORDER BY o.slug;
