CREATE TABLE IF NOT EXISTS deva_accmed_enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_user_id BIGINT NOT NULL,
  client_user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  start_day TIMESTAMPTZ,
  days_left INTEGER,
  investment REAL,
  decision_matrix_status TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_deva_accmed_enrollments_provider_client_diff
    CHECK (provider_user_id <> client_user_id)
);

ALTER TABLE deva_accmed_enrollments
  ADD COLUMN IF NOT EXISTS start_day TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS days_left INTEGER,
  ADD COLUMN IF NOT EXISTS investment REAL,
  ADD COLUMN IF NOT EXISTS decision_matrix_status TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT;

ALTER TABLE deva_accmed_enrollments
  ALTER COLUMN status SET DEFAULT 'active';

CREATE UNIQUE INDEX IF NOT EXISTS uq_deva_accmed_enrollments_triplet_idx
  ON deva_accmed_enrollments (provider_user_id, client_user_id, product_id);

CREATE INDEX IF NOT EXISTS ix_deva_accmed_enrollments_provider_user_id
  ON deva_accmed_enrollments (provider_user_id);

CREATE INDEX IF NOT EXISTS ix_deva_accmed_enrollments_client_user_id
  ON deva_accmed_enrollments (client_user_id);

CREATE INDEX IF NOT EXISTS ix_deva_accmed_enrollments_product_id
  ON deva_accmed_enrollments (product_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chk_deva_accmed_enrollments_days_left_non_negative'
  ) THEN
    ALTER TABLE deva_accmed_enrollments
      ADD CONSTRAINT chk_deva_accmed_enrollments_days_left_non_negative
      CHECK (days_left IS NULL OR days_left >= 0);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chk_deva_accmed_enrollments_status_allowed'
  ) THEN
    ALTER TABLE deva_accmed_enrollments
      ADD CONSTRAINT chk_deva_accmed_enrollments_status_allowed
      CHECK (
        status IN (
          'active',
          'finished',
          'suspended',
          'canceled by client',
          'canceled by organization'
        )
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_deva_accmed_enrollments_provider_user_id'
  ) THEN
    ALTER TABLE deva_accmed_enrollments
      ADD CONSTRAINT fk_deva_accmed_enrollments_provider_user_id
      FOREIGN KEY (provider_user_id)
      REFERENCES deva_accmed_users (id)
      ON UPDATE RESTRICT
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_deva_accmed_enrollments_client_user_id'
  ) THEN
    ALTER TABLE deva_accmed_enrollments
      ADD CONSTRAINT fk_deva_accmed_enrollments_client_user_id
      FOREIGN KEY (client_user_id)
      REFERENCES deva_accmed_users (id)
      ON UPDATE RESTRICT
      ON DELETE RESTRICT;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_deva_accmed_enrollments_product_id'
  ) THEN
    ALTER TABLE deva_accmed_enrollments
      ADD CONSTRAINT fk_deva_accmed_enrollments_product_id
      FOREIGN KEY (product_id)
      REFERENCES deva_accmed_products (id)
      ON UPDATE RESTRICT
      ON DELETE RESTRICT;
  END IF;
END $$;

INSERT INTO deva_accmed_enrollments (
  provider_user_id,
  client_user_id,
  product_id,
  start_day,
  days_left,
  investment,
  decision_matrix_status,
  status,
  created_at,
  updated_at
)
SELECT
  p.id AS provider_user_id,
  c.id AS client_user_id,
  pr.id AS product_id,
  NOW() AS start_day,
  NULL::INTEGER AS days_left,
  NULL::REAL AS investment,
  NULL::TEXT AS decision_matrix_status,
  'active' AS status,
  NOW() AS created_at,
  NOW() AS updated_at
FROM deva_accmed_users AS p
JOIN deva_accmed_products AS pr
  ON pr.slug = 'mst_accmed'
JOIN deva_accmed_users AS c
  ON c.role = 'client'
WHERE p.id = 2
  AND p.role = 'provider'
ON CONFLICT (provider_user_id, client_user_id, product_id) DO UPDATE SET
  updated_at = EXCLUDED.updated_at;

-- Validacao rapida pos-migracao
SELECT COUNT(*) AS enrollments_total
FROM deva_accmed_enrollments;

SELECT
  provider_user_id,
  product_id,
  COUNT(*) AS linked_clients
FROM deva_accmed_enrollments
GROUP BY provider_user_id, product_id
ORDER BY provider_user_id, product_id;
