CREATE TABLE IF NOT EXISTS deva_accmed_product_metrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pillar_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  direction TEXT NOT NULL,
  unit TEXT,
  scoring_rules JSONB NOT NULL,
  score_type TEXT NOT NULL,
  min_score REAL,
  max_score REAL,
  max_score_basis TEXT,
  mcv REAL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_deva_accmed_product_metrics_pillar_slug_idx
  ON deva_accmed_product_metrics (pillar_id, slug);

CREATE INDEX IF NOT EXISTS ix_deva_accmed_product_metrics_pillar_id
  ON deva_accmed_product_metrics (pillar_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_deva_accmed_product_metrics_pillar_id'
  ) THEN
    ALTER TABLE deva_accmed_product_metrics
      ADD CONSTRAINT fk_deva_accmed_product_metrics_pillar_id
      FOREIGN KEY (pillar_id)
      REFERENCES deva_accmed_product_pillars (id)
      ON UPDATE RESTRICT
      ON DELETE RESTRICT;
  END IF;
END $$;

WITH source_rows (
  pillar_id_ref,
  name,
  slug,
  direction,
  unit,
  scoring_rules,
  score_type,
  min_score,
  max_score,
  max_score_basis,
  mcv,
  is_active
) AS (
  VALUES
    ('1', 'N° de consultas mensais', 'mtr_consultas-mensais', 'higher_better', '', '[{"points": 5, "condition": {"operator": "lt", "value": 15}}, {"points": 10, "condition": {"operator": "and", "min": 15, "max": 30}}, {"points": 20, "condition": {"operator": "gt", "value": 30}}]'::jsonb, 'static', 5.0, 20.0, 'MAX_VALUE', 10.0, TRUE),
    ('1', 'N° de MQLs', 'mtr_mqls', 'higher_better', '', '[{"points": 5, "condition": {"operator": "lte", "value": 30}}, {"points": 20, "condition": {"operator": "gt", "value": 30}}]'::jsonb, 'static', 5.0, 20.0, 'MAX_VALUE', 5.0, TRUE),
    ('2', 'N° de Leads', 'mtr_leads', 'higher_better', '', '[{"points": 5, "condition": {"operator": "lte", "value": 100}}, {"points": 10, "condition": {"operator": "and", "min": 101, "max": 150}}, {"points": 20, "condition": {"operator": "gt", "value": 150}}]'::jsonb, 'static', 5.0, 20.0, 'MAX_VALUE', 5.0, TRUE),
    ('2', 'N° de Ofertas', 'mtr_ofertas', 'higher_better', '', '[{"points": 5, "condition": {"operator": "lte", "value": 10}}, {"points": 10, "condition": {"operator": "and", "min": 11, "max": 20}}, {"points": 20, "condition": {"operator": "gt", "value": 20}}]'::jsonb, 'static', 5.0, 20.0, 'MAX_VALUE', 10.0, TRUE),
    ('2', 'Taxa de Conversão', 'mtr_taxa-conversao', 'higher_better', '%', '[{"points": 5, "condition": {"operator": "lt", "value": 50, "unit": "%"}}, {"points": 20, "condition": {"operator": "gte", "value": 50, "unit": "%"}}]'::jsonb, 'static', 5.0, 20.0, 'MAX_VALUE', 5.0, TRUE),
    ('2', 'Ticket médio', 'mtr_ticket-medio', 'higher_better', 'R$', '[{"points": 5, "condition": {"operator": "lt", "value": 10000, "unit": "R$"}}, {"points": 10, "condition": {"operator": "and", "min": 10000, "max": 20000, "unit": "R$"}}, {"points": 20, "condition": {"operator": "gt", "value": 20000, "unit": "R$"}}]'::jsonb, 'static', 5.0, 20.0, 'MAX_VALUE', 10.0, TRUE),
    ('2', 'Faturamento', 'mtr_faturamento', 'higher_better', 'R$', '[{"points": 5, "condition": {"operator": "lt", "value": 100000, "unit": "R$"}}, {"points": 10, "condition": {"operator": "and", "min": 100000, "max": 500000, "unit": "R$"}}, {"points": 20, "condition": {"operator": "gt", "value": 500000, "unit": "R$"}}]'::jsonb, 'static', 5.0, 20.0, 'MAX_VALUE', 10.0, TRUE),
    ('3', 'Engajamento', 'mtr_engajamento', 'higher_better', '', '[{"points": 5, "condition": {"description": "presenças", "operator": "gt", "value": 4}}, {"points": 5, "condition": {"description": "feedback", "operator": "gt", "value": 4}}, {"points": 10, "condition": {"description": "vídeo", "operator": "gt", "value": 4}}]'::jsonb, 'static', 5.0, 10.0, 'MAX_VALUE', 10.0, TRUE),
    ('3', 'Gratidão', 'mtr_gratidao', 'higher_better', 'pts', '[{"points_range": [1, 4], "condition": {"operator": "eq", "value": "respondeu"}}, {"points": 0, "condition": {"operator": "eq", "value": "não respondeu"}}]'::jsonb, 'range', 0.0, 4.0, 'MAX_RVALUE', 4.0, TRUE),
    ('3', 'NED', 'mtr_ned', 'higher_better', '', '[{"points": 1, "condition": {"operator": "lt", "value": 8}}, {"points": 5, "condition": {"operator": "gte", "value": 8}}]'::jsonb, 'static', 1.0, 5.0, 'MAX_VALUE', 5.0, TRUE),
    ('4', 'Reuniões Semanais?', 'mtr_reunioes-semanais', 'higher_better', '', '[{"points": 2, "condition": {"operator": "eq", "value": "Sim"}}, {"points": 0, "condition": {"operator": "eq", "value": "Não"}}]'::jsonb, 'static', 0.0, 2.0, 'MAX_VALUE', 2.0, TRUE),
    ('4', 'NPS', 'mtr_nps', 'higher_better', '', '[{"points": 0, "condition": {"operator": "lt", "value": 8}}, {"points": 2, "condition": {"operator": "gte", "value": 8}}]'::jsonb, 'static', 0.0, 2.0, 'MAX_VALUE', 2.0, TRUE),
    ('4', 'Processos', 'mtr_processos', 'higher_better', '', '[{"points": 5, "condition": {"description": "Vendas"}}, {"points": 5, "condition": {"description": "Operações"}}, {"points": 5, "condition": {"description": "RH"}}]'::jsonb, 'accumulative', 5.0, 15.0, 'MAX_OPT', 10.0, TRUE),
    ('4', 'Ferramentas básicas', 'mtr_ferramentas-basicas', 'higher_better', '', '[{"points": 5, "condition": {"description": "Prontuário"}}, {"points": 5, "condition": {"description": "CRM"}}, {"points": 5, "condition": {"description": "Fluxo de Caixa/DRE"}}]'::jsonb, 'accumulative', 5.0, 15.0, 'MAX_OPT', 10.0, TRUE),
    ('5', 'N° de Serviços', 'mtr_numero-servicos', 'higher_better', '', '[{"points": 2, "condition": {"description": "Para cada serviço oferecido"}}]'::jsonb, 'unrestricted_sum', 0.0, 10.0, 'MCV', 6.0, TRUE),
    ('5', 'N° de Produtos Digitais', 'mtr_numero-produtos-digitais', 'higher_better', '', '[{"points": 5, "condition": {"description": "Para cada produto digital oferecido"}}]'::jsonb, 'unrestricted_sum', 0.0, 10.0, 'MCV', 0.0, TRUE)
)
INSERT INTO deva_accmed_product_metrics (
  pillar_id,
  name,
  slug,
  direction,
  unit,
  scoring_rules,
  score_type,
  min_score,
  max_score,
  max_score_basis,
  mcv,
  is_active,
  created_at,
  updated_at
)
SELECT
  p.id AS pillar_id,
  s.name,
  s.slug,
  s.direction,
  s.unit,
  s.scoring_rules,
  s.score_type,
  s.min_score,
  s.max_score,
  s.max_score_basis,
  s.mcv,
  s.is_active,
  NOW() AS created_at,
  NOW() AS updated_at
FROM source_rows AS s
JOIN deva_accmed_product_pillars AS p
  ON p.product_id = 1
 AND p.id = CAST(s.pillar_id_ref AS BIGINT)
ON CONFLICT (pillar_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  direction = EXCLUDED.direction,
  unit = EXCLUDED.unit,
  scoring_rules = EXCLUDED.scoring_rules,
  score_type = EXCLUDED.score_type,
  min_score = EXCLUDED.min_score,
  max_score = EXCLUDED.max_score,
  max_score_basis = EXCLUDED.max_score_basis,
  mcv = EXCLUDED.mcv,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

-- Validacao rapida pos-migracao
SELECT
  p.slug AS pillar_slug,
  COUNT(m.id) AS metrics_count
FROM deva_accmed_product_pillars AS p
LEFT JOIN deva_accmed_product_metrics AS m
  ON m.pillar_id = p.id
WHERE p.product_id = 1
GROUP BY p.slug
ORDER BY p.slug;

SELECT COUNT(*) AS metrics_total
FROM deva_accmed_product_metrics;