CREATE TABLE IF NOT EXISTS deva_accmed_product_pillars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  slug TEXT NOT NULL,
  order_index INTEGER NOT NULL,
  metadata JSONB,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_deva_accmed_product_pillars_product_slug_idx
  ON deva_accmed_product_pillars (product_id, slug);

CREATE INDEX IF NOT EXISTS ix_deva_accmed_product_pillars_product_id
  ON deva_accmed_product_pillars (product_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_deva_accmed_product_pillars_product_id'
  ) THEN
    ALTER TABLE deva_accmed_product_pillars
      ADD CONSTRAINT fk_deva_accmed_product_pillars_product_id
      FOREIGN KEY (product_id)
      REFERENCES deva_accmed_products (id)
      ON UPDATE RESTRICT
      ON DELETE RESTRICT;
  END IF;
END $$;

INSERT INTO deva_accmed_product_pillars (
  product_id,
  name,
  slug,
  order_index,
  metadata,
  is_active
) VALUES
  (
    1,
    'Captação',
    'men_accmed_plr_cap',
    1,
    '{"axis_sub": ""}'::jsonb,
    TRUE
  ),
  (
    1,
    'Vendas',
    'men_accmed_plr_vendas',
    2,
    '{"axis_sub": ""}'::jsonb,
    TRUE
  ),
  (
    1,
    'Mentalidade',
    'men_accmed_plr_mentalidade',
    3,
    '{"axis_sub": ""}'::jsonb,
    TRUE
  ),
  (
    1,
    'Gestão',
    'men_accmed_plr_gestao',
    4,
    '{"axis_sub": ""}'::jsonb,
    TRUE
  ),
  (
    1,
    'Repertório',
    'men_accmed_plr_repertorio',
    5,
    '{"axis_sub": ""}'::jsonb,
    TRUE
  )
ON CONFLICT (product_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  order_index = EXCLUDED.order_index,
  metadata = EXCLUDED.metadata,
  is_active = EXCLUDED.is_active;

-- Validacao rapida pos-migracao
SELECT
  product_id,
  COUNT(*) AS pillars_count
FROM deva_accmed_product_pillars
GROUP BY product_id
ORDER BY product_id;
