WITH source_rows (
  pillar_id_ref,
  name,
  slug,
  direction,
  unit,
  scoring_rules,
  score_type,
  min_score,
  max_score,
  max_score_basis,
  mcv,
  is_active
) AS (
  VALUES
    (
      '1',
      'N° de consultas mensais',
      'mtr_consultas-mensais',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "number"}, "scoring": {"mode": "first_match", "rules": [{"when": {"op": "lt", "value": 15}, "then": {"assign": 5}}, {"when": {"range": {"min": 15, "max": 30}}, "then": {"assign": 10}}, {"when": {"op": "gt", "value": 30}, "then": {"assign": 20}}]}, "normalization": {"basis": "max_score", "value": 20}}'::jsonb,
      'static',
      5.0,
      20.0,
      'MAX_VALUE',
      10.0,
      TRUE
    ),
    (
      '1',
      'N° de MQLs',
      'mtr_mqls',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "number"}, "scoring": {"mode": "first_match", "rules": [{"when": {"op": "lte", "value": 30}, "then": {"assign": 5}}, {"when": {"op": "gt", "value": 30}, "then": {"assign": 20}}]}, "normalization": {"basis": "max_score", "value": 20}}'::jsonb,
      'static',
      5.0,
      20.0,
      'MAX_VALUE',
      5.0,
      TRUE
    ),
    (
      '2',
      'N° de Leads',
      'mtr_leads',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "number"}, "scoring": {"mode": "first_match", "rules": [{"when": {"op": "lte", "value": 100}, "then": {"assign": 5}}, {"when": {"range": {"min": 101, "max": 150}}, "then": {"assign": 10}}, {"when": {"op": "gt", "value": 150}, "then": {"assign": 20}}]}, "normalization": {"basis": "max_score", "value": 20}}'::jsonb,
      'static',
      5.0,
      20.0,
      'MAX_VALUE',
      5.0,
      TRUE
    ),
    (
      '2',
      'N° de Ofertas',
      'mtr_ofertas',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "number"}, "scoring": {"mode": "first_match", "rules": [{"when": {"op": "lte", "value": 10}, "then": {"assign": 5}}, {"when": {"range": {"min": 11, "max": 20}}, "then": {"assign": 10}}, {"when": {"op": "gt", "value": 20}, "then": {"assign": 20}}]}, "normalization": {"basis": "max_score", "value": 20}}'::jsonb,
      'static',
      5.0,
      20.0,
      'MAX_VALUE',
      10.0,
      TRUE
    ),
    (
      '2',
      'Taxa de Conversão',
      'mtr_taxa-conversao',
      'higher_better',
      '%',
      '{"version": 2, "input": {"kind": "number", "unit": "%"}, "scoring": {"mode": "first_match", "rules": [{"when": {"op": "lt", "value": 50}, "then": {"assign": 5}}, {"when": {"op": "gte", "value": 50}, "then": {"assign": 20}}]}, "normalization": {"basis": "max_score", "value": 20}}'::jsonb,
      'static',
      5.0,
      20.0,
      'MAX_VALUE',
      5.0,
      TRUE
    ),
    (
      '2',
      'Ticket médio',
      'mtr_ticket-medio',
      'higher_better',
      'R$',
      '{"version": 2, "input": {"kind": "number", "unit": "R$"}, "scoring": {"mode": "first_match", "rules": [{"when": {"op": "lt", "value": 10000}, "then": {"assign": 5}}, {"when": {"range": {"min": 10000, "max": 20000}}, "then": {"assign": 10}}, {"when": {"op": "gt", "value": 20000}, "then": {"assign": 20}}]}, "normalization": {"basis": "max_score", "value": 20}}'::jsonb,
      'static',
      5.0,
      20.0,
      'MAX_VALUE',
      10.0,
      TRUE
    ),
    (
      '2',
      'Faturamento',
      'mtr_faturamento',
      'higher_better',
      'R$',
      '{"version": 2, "input": {"kind": "number", "unit": "R$"}, "scoring": {"mode": "first_match", "rules": [{"when": {"op": "lt", "value": 100000}, "then": {"assign": 5}}, {"when": {"range": {"min": 100000, "max": 500000}}, "then": {"assign": 10}}, {"when": {"op": "gt", "value": 500000}, "then": {"assign": 20}}]}, "normalization": {"basis": "max_score", "value": 20}}'::jsonb,
      'static',
      5.0,
      20.0,
      'MAX_VALUE',
      10.0,
      TRUE
    ),
    (
      '3',
      'Engajamento',
      'mtr_engajamento',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "object"}, "scoring": {"mode": "sum_matches", "rules": [{"key": "presencas", "label": "presenças", "when": {"any": [{"field": "presencas", "op": "gt", "value": 4}, {"field": "presenças", "op": "gt", "value": 4}]}, "then": {"assign": 5}}, {"key": "feedback", "label": "feedback", "when": {"field": "feedback", "op": "gt", "value": 4}, "then": {"assign": 5}}, {"key": "video", "label": "vídeo", "when": {"any": [{"field": "video", "op": "gt", "value": 4}, {"field": "vídeo", "op": "gt", "value": 4}]}, "then": {"assign": 10}}]}, "normalization": {"basis": "max_score", "value": 10}}'::jsonb,
      'static',
      5.0,
      10.0,
      'MAX_VALUE',
      10.0,
      TRUE
    ),
    (
      '3',
      'Gratidão',
      'mtr_gratidao',
      'higher_better',
      'pts',
      '{"version": 2, "input": {"kind": "string", "unit": "pts"}, "scoring": {"mode": "first_match", "rules": [{"when": {"op": "eq", "value": "respondeu"}, "then": {"assign_range": {"min": 1, "max": 4, "policy": "max"}}}, {"when": {"op": "eq", "value": "não respondeu"}, "then": {"assign": 0}}]}, "normalization": {"basis": "max_range", "value": 4}}'::jsonb,
      'range',
      0.0,
      4.0,
      'MAX_RVALUE',
      4.0,
      TRUE
    ),
    (
      '3',
      'NED',
      'mtr_ned',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "number"}, "scoring": {"mode": "first_match", "rules": [{"when": {"op": "lt", "value": 8}, "then": {"assign": 1}}, {"when": {"op": "gte", "value": 8}, "then": {"assign": 5}}]}, "normalization": {"basis": "max_score", "value": 5}}'::jsonb,
      'static',
      1.0,
      5.0,
      'MAX_VALUE',
      5.0,
      TRUE
    ),
    (
      '4',
      'Reuniões Semanais?',
      'mtr_reunioes-semanais',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "string"}, "scoring": {"mode": "first_match", "rules": [{"when": {"op": "eq", "value": "Sim"}, "then": {"assign": 2}}, {"when": {"op": "eq", "value": "Não"}, "then": {"assign": 0}}]}, "normalization": {"basis": "max_score", "value": 2}}'::jsonb,
      'static',
      0.0,
      2.0,
      'MAX_VALUE',
      2.0,
      TRUE
    ),
    (
      '4',
      'NPS',
      'mtr_nps',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "number"}, "scoring": {"mode": "first_match", "rules": [{"when": {"op": "lt", "value": 8}, "then": {"assign": 0}}, {"when": {"op": "gte", "value": 8}, "then": {"assign": 2}}]}, "normalization": {"basis": "max_score", "value": 2}}'::jsonb,
      'static',
      0.0,
      2.0,
      'MAX_VALUE',
      2.0,
      TRUE
    ),
    (
      '4',
      'Processos',
      'mtr_processos',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "set"}, "scoring": {"mode": "sum_matches", "rules": [{"key": "sales_process", "label": "Vendas", "when": {"contains_any": ["sales_process", "vendas"]}, "then": {"assign": 5}}, {"key": "operations_process", "label": "Operações", "when": {"contains_any": ["operations_process", "operações", "operacoes"]}, "then": {"assign": 5}}, {"key": "people_process", "label": "RH", "when": {"contains_any": ["people_process", "rh"]}, "then": {"assign": 5}}]}, "normalization": {"basis": "max_score", "value": 15}}'::jsonb,
      'accumulative',
      5.0,
      15.0,
      'MAX_OPT',
      10.0,
      TRUE
    ),
    (
      '4',
      'Ferramentas básicas',
      'mtr_ferramentas-basicas',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "set"}, "scoring": {"mode": "sum_matches", "rules": [{"key": "medical_record", "label": "Prontuário", "when": {"contains_any": ["medical_record", "prontuário", "prontuario"]}, "then": {"assign": 5}}, {"key": "crm", "label": "CRM", "when": {"contains_any": ["crm"]}, "then": {"assign": 5}}, {"key": "cash_flow_dre", "label": "Fluxo de Caixa/DRE", "when": {"contains_any": ["cash_flow_dre", "fluxo de caixa/dre"]}, "then": {"assign": 5}}]}, "normalization": {"basis": "max_score", "value": 15}}'::jsonb,
      'accumulative',
      5.0,
      15.0,
      'MAX_OPT',
      10.0,
      TRUE
    ),
    (
      '5',
      'N° de Serviços',
      'mtr_numero-servicos',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "number"}, "scoring": {"mode": "per_unit", "points_per_unit": 2}, "normalization": {"basis": "mcv", "value": 6}}'::jsonb,
      'unrestricted_sum',
      0.0,
      10.0,
      'MCV',
      6.0,
      TRUE
    ),
    (
      '5',
      'N° de Produtos Digitais',
      'mtr_numero-produtos-digitais',
      'higher_better',
      '',
      '{"version": 2, "input": {"kind": "number"}, "scoring": {"mode": "per_unit", "points_per_unit": 5}, "normalization": {"basis": "mcv"}}'::jsonb,
      'unrestricted_sum',
      0.0,
      10.0,
      'MCV',
      0.0,
      TRUE
    )
)
INSERT INTO deva_accmed_product_metrics (
  pillar_id,
  name,
  slug,
  direction,
  unit,
  scoring_rules,
  score_type,
  min_score,
  max_score,
  max_score_basis,
  mcv,
  is_active,
  created_at,
  updated_at
)
SELECT
  p.id AS pillar_id,
  s.name,
  s.slug,
  s.direction,
  s.unit,
  s.scoring_rules,
  s.score_type,
  s.min_score,
  s.max_score,
  s.max_score_basis,
  s.mcv,
  s.is_active,
  NOW() AS created_at,
  NOW() AS updated_at
FROM source_rows AS s
JOIN deva_accmed_product_pillars AS p
  ON p.product_id = 1
 AND p.id = CAST(s.pillar_id_ref AS BIGINT)
ON CONFLICT (pillar_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  direction = EXCLUDED.direction,
  unit = EXCLUDED.unit,
  scoring_rules = EXCLUDED.scoring_rules,
  score_type = EXCLUDED.score_type,
  min_score = EXCLUDED.min_score,
  max_score = EXCLUDED.max_score,
  max_score_basis = EXCLUDED.max_score_basis,
  mcv = EXCLUDED.mcv,
  is_active = EXCLUDED.is_active,
  updated_at = EXCLUDED.updated_at;

SELECT
  slug,
  scoring_rules->>'version' AS scoring_rules_version,
  jsonb_typeof(scoring_rules) AS scoring_rules_type,
  updated_at
FROM deva_accmed_product_metrics
WHERE slug IN (
  'mtr_consultas-mensais',
  'mtr_faturamento',
  'mtr_gratidao',
  'mtr_processos',
  'mtr_numero-servicos'
)
ORDER BY slug;
